/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fc_24_bot_java2;



public class App {
    public static void main(String[] args) {
        var login = new LoginPage("overthedwainbow@gmail.com", "Daniels2002");
        login.login();
        login.authenticate();
        login.loginWebApp();
        var failCount = 0 ;
        var succesCount = 0;

        var webapp = new WebApp(login.getDriver());
        webapp.goToTransfers();
        webapp.goToTransferMarket();
        var playerName = "Coutinho";
        var playerPrice = "2300";
        webapp.enterPlayerName(playerName);
        webapp.setMaxBuyPrice(playerPrice);
        var initCoins = webapp.getCoins();
        var attempts = 0;
        while(true)
        {
            System.out.println("Success: " + succesCount + " Fail: " + failCount);
            if(attempts > 15)
            {
                webapp.resetMinBuyPrice();
                attempts= 0 ;
            }
            webapp.incrementMinBuyPrice();
            webapp.search();
            if(webapp.noResult())
            {
                attempts++;
                continue;
            }
            if (webapp.buyPlayer())
            {
                if(webapp.getCoins()<initCoins)
                {
                    System.out.println("Succesfully bought player");
                    succesCount++;
                    initCoins = webapp.getCoins();
                }
                else
                {
                    System.out.println("Failed to buy player");
                    failCount++;
                }
                attempts++;
            }
            else
            {
                webapp.reset(playerName);
            }
            
        }

    }
}
